### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by dhruvrana72** [adjoint-io/uplink-sdk-python#6]
Hi,
I am not sure whether I should be posting it here or not. 
When a user issue tokens, don't you think tokens should be added to his wallet or account by default?
1. When I create an asset first transfer happens, but for next transfer it shows insufficient funds.
2. But when I create asset and transfer it to myself, then it works as normal wallet transfer but shows error with asset type.
Here's the link to the screen cast for 1:
https://drive.google.com/file/d/1YtjvnTdhki1rg5iH4xCqzmkil4UpkdTI/view?usp=sharing

Here's the link to the screen cast for 2:
https://drive.google.com/file/d/15vy3WZJwVeh1vtVglGQ3N7m5vonnwcdq/view?usp=sharing

Am I doing something wrong ?

Thanks

**Comment by dhruvrana72** [comment]
So I guess what's happening is when issuer make the first transfer it doesn't matter,  whom he selects to transfer the token, the token gets transferred to his account only. After, that next transfer is based on the holdings not on the asset supply and issuer. 
I am not sure whether this should work like this. (not sure bug or feature :| )
any advise/help?
Thanks

**Comment by tdietert** [comment]
Yes, this is a know bug, and a fix has been implemented with the addition of a `Circulate` transaction. In order to bring an amount of an asset into "circulation" the issuer of the asset must issue a `CirculateTransaction`, taking that amount of supply of the asset and adding it to the issuer's _holdings_. Then, the issuer can "transfer" an amount of his holdings to any other account (address) in the network. Please stand by for the next release, which should happen within the next few days.

Regarding an initial question of yours:
We have discussed at length whether or not the supply of an issued asset should be directly made available for the asset issuer to transfer, but have decided it against it, as in some use cases asset issuers would prefer to not circulate the entire supply of the asset, having more fine grained control and extra assurance that they won't accidentally transfer more than a certain amount of holdings to other accounts. Separating the notion of _circulation_ of an asset's supply and _transference_ of an account's holdings of an asset gives a more precise way for the asset issuer and asset holders to interact with the ledger.

**Comment by sdiehl** [comment]
Per this discussion, the 1.1 release has been shipped which has the `Circulate` transaction.

https://github.com/adjoint-io/uplink/releases/tag/1.1

Let us know if this fixes your issue.

**Comment by dhruvrana72** [comment]
Yes, this one is fixed.
Thanks alot.
